---
kind: pipeline
type: docker
name: default

steps:
  - name: essai-api
    image: golang:1.12
    commands:
      - go build
      - go test

  trigger:
    branch:
      - master
    event:
      - push
